### ISSUE TITLE
Problems when using as host on Rancher + K8s

### ISSUE THREAD

**Issue by rjricardo** [scaleway/image-builder#13]
Hello,

I've tried to use this image in a host to add it into a Kubernetes cluster orchestrated with Rancher. With this image the Kubelet and Proxy processes fail to start multiple times. When they finally do, they have trouble communicating and the node does not get registered with the cluster and is not usable for deployments.

I later tried using your default Ubuntu 15.10 Wily image and installed docker on it. Worked much better. Containers instantiated quicker and nodes registered themselves successfully with the cluster. 

However, I'd rather use this image because of aufs storage driver. Seems more production-ready.

Could the image have something to do with this?
Has anybody tried Rancher + Kubernetes on Scaleway?

Many thanks.

**Comment by sieben** [comment]
@jtherin ^

**Comment by rjricardo** [comment]
Hi @chmod666org , this issue was over 2 years ago. After no response, I must've forgotten to come back to close this. New versions of Kubernetes have no problem. Thanks for getting back to me!
