### ISSUE TITLE
cannot execute 'tag'

### ISSUE THREAD

**Issue by pierrepinon** [scaleway/image-builder#18]
Hello,

When i execute "make image_on_local" the script return **FATA[0000] cannot execute 'tag': No such bootscript: latest**

This message is displayed after this step : **[+] Creating an image based of the snapshot**

**Comment by TobiasBales** [comment]
You can remove the
`IMAGE_BOOTSCRIPT =      stable` 
line from your `Makefile` then it should work.

It seems to be that the bootscript handling/naming was changed somehow.
