### ISSUE TITLE
Instructions in readme fail on amd_64

### ISSUE THREAD

**Issue by ewoutp** [scaleway/image-builder#6]
To build an amd64 image, you need a 150GB volume, so the first run command in the readme (to start the image builder) needs `--commercial-type=C2S|C2M|C2L` added.

**Comment by QuentinPerez** [comment]
Hi @ewoutp,

Why do you need 150G to build an amd64 image ?
All scaleway images will have a default size disk of 50G to boot on VC1.
Can you explain your needs ?

**Comment by ewoutp** [comment]
I don't need it, but at the time the image-builder needed it (don't know why). 
I think that has been fixed now.
